//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REalimenta1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alimento
    {
        public int alimento_id { get; set; }
        public System.DateTime validade { get; set; }
        public int quantidade { get; set; }
        public string nome { get; set; }
        public string detalhes { get; set; }
        public string origem { get; set; }
        public int mercado_id { get; set; }
        public int categoriaalimento_id { get; set; }
    
        public virtual categoria_alimento categoria_alimento { get; set; }
        public virtual mercado mercado { get; set; }
    }
}
