//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REalimenta1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doacao
    {
        public int doacao_id { get; set; }
        public int ong_id { get; set; }
        public int mercado_id { get; set; }
        public int alimento_id { get; set; }
        public int higiene_id { get; set; }
    
        public virtual categoria_alimento categoria_alimento { get; set; }
        public virtual mercado mercado { get; set; }
    }
}
