//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REalimenta1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_realimentaEntities : DbContext
    {
        public bd_realimentaEntities()
            : base("name=bd_realimentaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alimento> alimento { get; set; }
        public virtual DbSet<categoria_alimento> categoria_alimento { get; set; }
        public virtual DbSet<categoria_higiene> categoria_higiene { get; set; }
        public virtual DbSet<continente> continente { get; set; }
        public virtual DbSet<doacao> doacao { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<higiene> higiene { get; set; }
        public virtual DbSet<localidade> localidade { get; set; }
        public virtual DbSet<mercado> mercado { get; set; }
        public virtual DbSet<ong> ong { get; set; }
        public virtual DbSet<pais> pais { get; set; }
    }
}
